# LLaMA_Factory Installation

In [1]:

%rm -rf LLaMA-Factory

!git clone https://github.com/hiyouga/LLaMA-Factory.git

%cd LLaMA-Factory

!git checkout d325a1a7c7052946bd3b1e666459222c06ae5cb5

%ls

!pip install -e .[torch,bitsandbytes]

Cloning into 'LLaMA-Factory'...
remote: Enumerating objects: 24425, done.
remote: Total 24425 (delta 0), reused 0 (delta 0), pack-reused 24425 (from 1)
Receiving objects: 100% (24425/24425), 12.06 MiB | 25.41 MiB/s, done.
Resolving deltas: 100% (17622/17622), done.
/kaggle/working/LLaMA-Factory
fatal: reference is not a tree: d325a1a7c7052946bd3b1e666459222c06ae5cb5
assets/       docker/    Makefile        README.md         scripts/  tests/
CITATION.cff  examples/  MANIFEST.in     README_zh.md      setup.py  tests_v1/
data/         LICENSE    pyproject.toml  requirements.txt  src/
Obtaining file:///kaggle/working/LLaMA-Factory
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: transformers!=4.52.0,!=4.57.0,<=4.57.1,>=4.49.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (4.51.3)
Requirement already satisfied: datasets<=4.0.0,>=2.16.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (3.6.0)
Requirement already satisfied: accelerate<=1.11.0,>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (1.5.2)
Requirement already satisfied: peft<=0.17.1,>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (0.14.0)
Collecting trl<=0.9.6,>=0.8.6 (from llamafactory==0.9.4.dev0)
  Downloading trl-0.9.6-py3-none-any.whl.metadata (12 kB)
Collecting gradio<=5.45.0,>=4.38.0 (from llamafactory==0.9.4.dev0)
  Downloading gradio-5.45.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: matplotlib>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (3.7.2)
Collecting tyro<0.9.0 (from llamafactory==0.9.4.dev0)
  Downloading tyro-0.8.14-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (0.8.1)
Requirement already satisfied: numpy<2.0.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (1.26.4)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (1.15.2)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (0.2.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (0.9.0)
Collecting modelscope>=1.14.0 (from llamafactory==0.9.4.dev0)
  Downloading modelscope-1.31.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: hf-transfer in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (0.1.9)
Requirement already satisfied: safetensors<=0.5.3 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (0.5.3)
Collecting fire (from llamafactory==0.9.4.dev0)
  Downloading fire-0.7.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (2.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (25.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (3.20.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (6.0.2)
Collecting pydantic<=2.10.6 (from llamafactory==0.9.4.dev0)
  Downloading pydantic-2.10.6-py3-none-any.whl.metadata (30 kB)
Collecting uvicorn (from llamafactory==0.9.4.dev0)
  Downloading uvicorn-0.38.0-py3-none-any.whl.metadata (6.8 kB)
Collecting fastapi (from llamafactory==0.9.4.dev0)
  Downloading fastapi-0.121.2-py3-none-any.whl.metadata (28 kB)
Collecting sse-starlette (from llamafactory==0.9.4.dev0)
  Downloading sse_starlette-3.0.3-py3-none-any.whl.metadata (12 kB)
Collecting av (from llamafactory==0.9.4.dev0)
  Downloading av-16.0.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: librosa in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (0.11.0)
Requirement already satisfied: propcache!=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (0.3.1)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.15.0 in /usr/local/lib/python3.11/dist-packages (from llamafactory==0.9.4.dev0) (0.21.0+cu124)
Collecting bitsandbytes>=0.39.0 (from llamafactory==0.9.4.dev0)
  Downloading bitsandbytes-0.48.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate<=1.11.0,>=1.3.0->llamafactory==0.9.4.dev0) (7.0.0)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from accelerate<=1.11.0,>=1.3.0->llamafactory==0.9.4.dev0) (0.31.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.4.dev0) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.4.dev0) (19.0.1)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.4.dev0) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.4.dev0) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.4.dev0) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.4.dev0) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.4.dev0) (0.70.16)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.4.dev0)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (22.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (4.9.0)
Collecting brotli>=1.1.0 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading brotli-1.2.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.1 kB)
Collecting ffmpy (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading ffmpy-1.0.0-py3-none-any.whl.metadata (3.0 kB)
Collecting gradio-client==1.13.0 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading gradio_client-1.13.0-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (0.28.1)
Collecting huggingface-hub>=0.21.0 (from accelerate<=1.11.0,>=1.3.0->llamafactory==0.9.4.dev0)
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (3.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (3.10.16)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (11.1.0)
Requirement already satisfied: pydub in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (0.25.1)
Collecting python-multipart>=0.0.18 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Collecting ruff>=0.9.3 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading ruff-0.14.5-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting safehttpx<0.2.0,>=0.1.6 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading safehttpx-0.1.7-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading starlette-0.50.0-py3-none-any.whl.metadata (6.3 kB)
Collecting tomlkit<0.14.0,>=0.12.0 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading tomlkit-0.13.3-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (0.15.2)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.11/dist-packages (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (4.13.2)
Requirement already satisfied: websockets<16.0,>=10.0 in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.13.0->gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (15.0.1)
Collecting starlette<1.0,>=0.40.0 (from gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0)
  Downloading starlette-0.49.3-py3-none-any.whl.metadata (6.4 kB)
Collecting annotated-doc>=0.0.2 (from fastapi->llamafactory==0.9.4.dev0)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.4.dev0) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.4.dev0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.4.dev0) (4.57.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.4.dev0) (1.4.8)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.4.dev0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.4.dev0) (2.9.0.post0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from modelscope>=1.14.0->llamafactory==0.9.4.dev0) (75.2.0)
Requirement already satisfied: urllib3>=1.26 in /usr/local/lib/python3.11/dist-packages (from modelscope>=1.14.0->llamafactory==0.9.4.dev0) (2.4.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy<2.0.0->llamafactory==0.9.4.dev0) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy<2.0.0->llamafactory==0.9.4.dev0) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy<2.0.0->llamafactory==0.9.4.dev0) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy<2.0.0->llamafactory==0.9.4.dev0) (2025.1.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy<2.0.0->llamafactory==0.9.4.dev0) (2022.1.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy<2.0.0->llamafactory==0.9.4.dev0) (2.4.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.0.0->llamafactory==0.9.4.dev0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.0.0->llamafactory==0.9.4.dev0) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<=2.10.6->llamafactory==0.9.4.dev0) (0.7.0)
Collecting pydantic-core==2.27.2 (from pydantic<=2.10.6->llamafactory==0.9.4.dev0)
  Downloading pydantic_core-2.27.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->llamafactory==0.9.4.dev0) (3.4.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->llamafactory==0.9.4.dev0) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->llamafactory==0.9.4.dev0) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->llamafactory==0.9.4.dev0) (12.4.127)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=2.0.0->llamafactory==0.9.4.dev0)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=2.0.0->llamafactory==0.9.4.dev0)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=2.0.0->llamafactory==0.9.4.dev0)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=2.0.0->llamafactory==0.9.4.dev0)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=2.0.0->llamafactory==0.9.4.dev0)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=2.0.0->llamafactory==0.9.4.dev0)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->llamafactory==0.9.4.dev0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->llamafactory==0.9.4.dev0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->llamafactory==0.9.4.dev0) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=2.0.0->llamafactory==0.9.4.dev0)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->llamafactory==0.9.4.dev0) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->llamafactory==0.9.4.dev0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0.0->llamafactory==0.9.4.dev0) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers!=4.52.0,!=4.57.0,<=4.57.1,>=4.49.0->llamafactory==0.9.4.dev0) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers!=4.52.0,!=4.57.0,<=4.57.1,>=4.49.0->llamafactory==0.9.4.dev0) (0.21.1)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.11/dist-packages (from tyro<0.9.0->llamafactory==0.9.4.dev0) (0.16)
Requirement already satisfied: rich>=11.1.0 in /usr/local/lib/python3.11/dist-packages (from tyro<0.9.0->llamafactory==0.9.4.dev0) (14.0.0)
Collecting shtab>=1.5.6 (from tyro<0.9.0->llamafactory==0.9.4.dev0)
  Downloading shtab-1.7.2-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/dist-packages (from uvicorn->llamafactory==0.9.4.dev0) (8.1.8)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/dist-packages (from uvicorn->llamafactory==0.9.4.dev0) (0.14.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.11/dist-packages (from fire->llamafactory==0.9.4.dev0) (3.0.1)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (3.0.1)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (0.60.0)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (1.2.2)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (1.5.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (4.4.2)
Requirement already satisfied: soundfile>=0.12.1 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (0.13.1)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (0.5.0.post1)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.11/dist-packages (from librosa->llamafactory==0.9.4.dev0) (1.1.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.11/dist-packages (from omegaconf->llamafactory==0.9.4.dev0) (4.9.3)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (1.3.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.4.dev0) (3.11.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1.0,>=0.24.1->gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1.0,>=0.24.1->gradio<=5.45.0,>=4.38.0->llamafactory==0.9.4.dev0) (1.0.7)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub>=0.21.0->accelerate<=1.11.0,>=1.3.0->llamafactory==0.9.4.dev0)
  Downloading hf_xet-1.2.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.51.0->librosa->llamafactory==0.9.4.dev0) (0.43.0)

# Login to HF

In [ ]:
hf_token = 'your_huggingface_token_here'
!huggingface-cli login --token {hf_token}

⚠️  Warning: 'huggingface-cli login' is deprecated. Use 'hf auth login' instead.
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `hf`CLI if you want to set the git credential as well.
Token is valid (permission: fineGrained).
The token `lama` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
The current active token is: `lama`

# Dataset Preparation
- add `system` Prompt
- add `instruction` - User Prompt
- add `input` - Text
- add `output` - Ground-Truth for Generation

In [3]:
import json
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
# same data with summaries 
file_path  = "hf://datasets/vishnupriyavr/wiki-movie-plots-with-summaries/wiki_movie_plots_deduped_with_summaries.csv"

df = pd.read_csv(file_path)
df.head(2)

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot,PlotSummary
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr...",Carrie Nation and her followers burst into a s...
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov...","The moon, painted with a smiling face hangs ov..."

In [ ]:
# reanme to match expected column names in llama-factory
df = df.rename(columns={"Plot": "input"})

df.head(2)

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,input,PlotSummary
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr...",Carrie Nation and her followers burst into a s...
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov...","The moon, painted with a smiling face hangs ov..."

#  `Summarization` taks

In [7]:
SYSTEM_PROMPT = "You are an expert detailed summarizer, Generate non-spoiler summaries."
INSTRUCTION_PROMPT = "Generate non-spoiler summary for the following text:\n"

In [ ]:
df["system"] = SYSTEM_PROMPT
df["instruction"] = INSTRUCTION_PROMPT

# Rename  
df = df.rename(columns={"PlotSummary": "output"})

df = df[["input", "output", "system", "instruction"]]

df.head(2)

,input,output,system,instruction
0,"A bartender is working at a saloon, serving dr...",Carrie Nation and her followers burst into a s...,"You are an expert detailed summarizer, Generat...",Generate non-spoiler summary for the following...
1,"The moon, painted with a smiling face hangs ov...","The moon, painted with a smiling face hangs ov...","You are an expert detailed summarizer, Generat...",Generate non-spoiler summary for the following...

# Splitting Data Train/Test

In [9]:
df.shape

(34886, 4)

In [10]:
# Split data
train_data, test_data = train_test_split(df, train_size=24000/34886, random_state=42)
train_data.shape, test_data.shape

((24000, 4), (10886, 4))

In [11]:
# To save a pandas DataFrame as a .jsonl (JSON Lines) file
TRAIN_FILE_PATH = "/kaggle/working/LLaMA-Factory/train.jsonl"
TEST_FILE_PATH = "/kaggle/working/LLaMA-Factory/test.jsonl"

train_data.to_json(TRAIN_FILE_PATH, orient="records", lines=True, force_ascii=False)
test_data.to_json(TEST_FILE_PATH, orient="records", lines=True, force_ascii=False)

 # Configure LLaMA-Factory for the new datasets

In [12]:
import os

dataset_info_path = "./data/dataset_info.json"

In [13]:
custom_dataset_entry = {
    "custom_finetune_train": {
        "file_name": TRAIN_FILE_PATH,
        "columns": {
            "system": "system",  
            "prompt": "instruction",
            "response": "output",
            "query": "input"    

        }
    },
    "custom_finetune_test": {
        "file_name": TEST_FILE_PATH,
        "columns": {
            "system": "system",    
            "prompt": "instruction", 
            "response": "output",
            "query": "input"        
        }
    }
}

In [14]:
if os.path.exists(dataset_info_path):
    with open(dataset_info_path, "r") as f:
        dataset_info = json.load(f)


# Add or update the custom dataset entry (extraction)
dataset_info.update(custom_dataset_entry)

# Write back the updated info
with open(dataset_info_path, "w") as f:
    json.dump(dataset_info, f, indent=2)

In [15]:
!tail -20 ./data/dataset_info.json

  },
  "custom_finetune_train": {
    "file_name": "/kaggle/working/LLaMA-Factory/train.jsonl",
    "columns": {
      "system": "system",
      "prompt": "instruction",
      "response": "output",
      "query": "input"
    }
  },
  "custom_finetune_test": {
    "file_name": "/kaggle/working/LLaMA-Factory/test.jsonl",
    "columns": {
      "system": "system",
      "prompt": "instruction",
      "response": "output",
      "query": "input"
    }
  }
}

## - Create `Training Configuration` File

In [ ]:
%%writefile ./examples/train_lora/summarization_finetune_gemma3.yaml

### model
model_name_or_path: google/gemma-3-270m-it    
trust_remote_code: true                  

### method
stage: sft                                
do_train: true                         
finetuning_type: lora                     
lora_rank: 64                            
lora_target: all                         

### dataset
dataset: custom_finetune_train     
eval_dataset: custom_finetune_test  
template: gemma                    
cutoff_len: 4096                         
max_samples: 10000                         
overwrite_cache: true                    
preprocessing_num_workers: 16          

### output
output_dir: ../finetuned_models/gemma3   
logging_steps: 10                      
save_steps: 500                          
plot_loss: false                         

### train
per_device_train_batch_size: 1      
gradient_accumulation_steps:  8        
learning_rate: 5.0e-5             
num_train_epochs: 1.0                   
lr_scheduler_type: cosine               
warmup_ratio: 0.1                       
bf16: true                               
ddp_timeout: 180000000                   

### eval
# val_size: 0.1                       
per_device_eval_batch_size: 1     
eval_strategy: steps                     
eval_steps: 100                          

report_to: none

Overwriting ./examples/train_lora/summarization_finetune_gemma3.yaml

 # Start Training

In [23]:
!llamafactory-cli train ./examples/train_lora/summarization_finetune_gemma3.yaml

2025-11-14 22:34:00.773808: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1763159640.799736    1393 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1763159640.807995    1393 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[INFO|2025-11-14 22:34:05] llamafactory.launcher:143 >> Initializing 2 distributed tasks at: 127.0.0.1:42575
W1114 22:34:07.076000 1406 torch/distributed/run.py:792]
W1114 22:34:07.076000 1406 torch/distributed/run.py:792] *****************************************
W1114 22:34:07.076000 1406 torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W1114 22:34:07.076000 1406 torch/distributed/run.py:792] *****************************************
2025-11-14 22:34:12.412794: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-11-14 22:34:12.413232: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1763159652.439383    1409 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1763159652.439790    1408 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1763159652.447180    1409 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1763159652.447748    1408 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[INFO|2025-11-14 22:34:20] llamafactory.hparams.parser:143 >> Set `ddp_find_unused_parameters` to False in DDP training since LoRA is enabled.
[INFO|2025-11-14 22:34:20] llamafactory.hparams.parser:468 >> Process rank: 0, world size: 2, device: cuda:0, distributed training: True, compute dtype: torch.bfloat16
[INFO|2025-11-14 22:34:20] llamafactory.hparams.parser:468 >> Process rank: 1, world size: 2, device: cuda:1, distributed training: True, compute dtype: torch.bfloat16
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:20,714 >> loading file tokenizer.model from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/tokenizer.model
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:20,714 >> loading file tokenizer.json from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/tokenizer.json
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:20,714 >> loading file added_tokens.json from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/added_tokens.json
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:20,714 >> loading file special_tokens_map.json from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/special_tokens_map.json
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:20,714 >> loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/tokenizer_config.json
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:20,714 >> loading file chat_template.jinja from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/chat_template.jinja
[INFO|configuration_utils.py:693] 2025-11-14 22:34:23,096 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/config.json
[INFO|configuration_utils.py:765] 2025-11-14 22:34:23,098 >> Model config Gemma3TextConfig {
  "_sliding_window_pattern": 6,
  "architectures": [
    "Gemma3ForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "attn_logit_softcapping": null,
  "bos_token_id": 2,
  "cache_implementation": "hybrid",
  "eos_token_id": 1,
  "final_logit_softcapping": null,
  "head_dim": 256,
  "hidden_activation": "gelu_pytorch_tanh",
  "hidden_size": 640,
  "initializer_range": 0.02,
  "intermediate_size": 2048,
  "layer_types": [
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "model_type": "gemma3_text",
  "num_attention_heads": 4,
  "num_hidden_layers": 18,
  "num_key_value_heads": 1,
  "pad_token_id": 0,
  "query_pre_attn_scalar": 256,
  "rms_norm_eps": 1e-06,
  "rope_local_base_freq": 10000.0,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": 512,
  "sliding_window_pattern": 6,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.51.3",
  "use_bidirectional_attention": false,
  "use_cache": true,
  "vocab_size": 262144
}

[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:23,181 >> loading file tokenizer.model from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/tokenizer.model
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:23,181 >> loading file tokenizer.json from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/tokenizer.json
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:23,181 >> loading file added_tokens.json from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/added_tokens.json
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:23,181 >> loading file special_tokens_map.json from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/special_tokens_map.json
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:23,181 >> loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/tokenizer_config.json
[INFO|tokenization_utils_base.py:2060] 2025-11-14 22:34:23,181 >> loading file chat_template.jinja from cache at /root/.cache/huggingface/hub/models--google--gemma-3-270m-it/snapshots/ac82b4e820549b854eebf28ce6dedaf9fdfa17b3/chat_template.jinja
[rank1]:[W1114 22:34:25.582375065 ProcessGroupNCCL.cpp:4561] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. Specify device_ids in barrier() to force use of a particular device, or call init_process_group() with a device_id.
[INFO|2025-11-14 22:34:25] llamafactory.data.template:143 >> Replace eos token: <end_of_turn>.
[INFO|2025-11-14 22:34:25] llamafactory.data.loader:143 >> Loading dataset /kaggle/working/LLaMA-Factory/train.jsonl...
Converting format of dataset (num_proc=16): 100%|█| 10000/10000 [00:01<00:00, 99
[INFO|2025-11-14 22:34:27] llamafactory.data.loader:143 >> Loading dataset /kaggle/working/LLaMA-Factory/test.jsonl...
Converting format of dataset (num_proc=16): 100%|█| 10000/10000 [00:00<00:00, 10
[rank0]:[W1114 22:34:28.941484932 ProcessGroupNCCL.cpp:4561] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. Specify device_ids in barrier() to force use of a particular device, or call init_process_group() with a device_id.
Running tokenizer on dataset (num_proc=16): 100%|█| 10000/10000 [00:30<00:00, 33
training example:
input_ids:
[2, 105, 2364, 107, 3048, 659, 614, 7710, 9813, 16000, 5482, 236764, 43550, 1908, 236772, 80960, 5624, 92681, 236761, 108, 43204, 1908, 236772, 80960, 5624, 12323, 573, 506, 2269, 1816, 236787, 108, 818, 4103, 5238, 506, 6176, 529, 59400, 532, 4649, 59183, 236764, 41639, 12958, 6730, 872, 528, 496, 6934, 532, 1845, 1679, 2433, 529, 70802, 236764, 16962, 7591, 236761, 59400, 54992, 699, 233496, 18404, 236764, 837, 3187, 6757, 1515, 1131, 13007, 1581, 1056, 625, 563, 711, 914, 15925, 236761, 3026, 506, 12958, 659, 22235, 699, 2528, 1308, 496, 6093, 236764, 901, 10741, 531, 6637, 3273, 24595, 532, 11010, 28754, 6211, 236761, 2195, 6077, 13808, 600, 52054, 14561, 699, 66776, 236764, 21071, 236764, 532, 2066, 33586, 740, 577, 69937, 236761, 251, 107, 7634, 6739, 910, 28754, 531, 496, 2263, 28754, 20220, 236764, 190923, 236764, 1015, 30047, 657, 3198, 1156, 17768, 532, 135766, 528, 49411, 36326, 18533, 236761, 190923, 5862, 4649, 59183, 531, 981, 607, 506, 11149, 236764, 3622, 668, 71193, 4649, 59183, 236789, 236751, 16601, 32893, 573, 532, 3756, 10592, 607, 17768, 236761, 190923, 992, 19518, 506, 12958, 15477, 496, 11149, 532, 496, 6343, 531, 6196, 28754, 6211, 236761, 251, 107, 2023, 4431, 563, 183792, 529, 190923, 236789, 236751, 42057, 8797, 4649, 59183, 236761, 59400, 35141, 531, 36577, 9097, 529, 28754, 699, 190923, 532, 6739, 1091, 236764, 3008, 607, 1070, 1032, 28754, 236764, 531, 496, 20220, 528, 189182, 236761, 669, 2731, 10842, 872, 1063, 218695, 236793, 59400, 563, 19153, 16825, 657, 506, 1032, 20220, 236764, 532, 1056, 668, 3590, 496, 3772, 607, 1070, 1758, 1015, 2729, 531, 6739, 506, 28754, 573, 1515, 236764, 901, 15256, 625, 618, 30575, 532, 2514, 506, 3273, 236761, 190923, 15249, 855, 532, 22899, 48087, 1090, 59400, 1131, 52054, 496, 3530, 6347, 529, 1494, 9832, 5898, 2066, 12268, 8733, 531, 1386, 872, 573, 914, 3967, 236761, 669, 12958, 659, 711, 6340, 7039, 529, 506, 39793, 529, 1494, 9832, 8733, 236761, 4210, 59400, 19945, 506, 8733, 236764, 4649, 59183, 7351, 531, 12693, 625, 236764, 840, 563, 7316, 236755, 7059, 532, 10500, 236761, 251, 107, 2023, 4431, 563, 78782, 532, 190923, 563, 16782, 236764, 14315, 506, 5589, 668, 563, 7757, 532, 10678, 59400, 531, 14317, 27248, 236761, 59400, 23378, 6701, 9480, 4782, 4649, 59183, 236789, 236751, 5946, 236789, 236751, 3155, 3097, 236764, 1308, 3131, 544, 17427, 236764, 914, 1852, 5946, 15249, 1515, 236761, 799, 496, 1626, 8317, 236764, 59400, 4716, 2065, 529, 506, 11149, 4649, 59183, 136533, 236761, 106, 107, 105, 4368, 107, 818, 4103, 5238, 506, 6176, 529, 59400, 532, 4649, 59183, 236764, 41639, 12958, 6730, 872, 528, 496, 6934, 532, 1845, 1679, 2433, 529, 70802, 236764, 16962, 7591, 236761, 59400, 54992, 699, 233496, 18404, 236764, 837, 3187, 6757, 1515, 1131, 13007, 1581, 1056, 625, 563, 711, 914, 15925, 236761, 3026, 506, 12958, 659, 22235, 699, 2528, 1308, 496, 6093, 236764, 901, 10741, 531, 6637, 3273, 24595, 532, 11010, 28754, 6211, 236761, 2195, 6739, 910, 28754, 531, 496, 2263, 28754, 20220, 236764, 190923, 236764, 1015, 30047, 657, 3198, 1156, 17768, 532, 135766, 528, 49411, 36326, 18533, 236761, 106, 107]
inputs:
<bos><start_of_turn>user
You are an expert detailed summarizer, Generate non-spoiler summaries.

Generate non-spoiler summary for the following text:

The film follows the lives of Arbor and Swifty, teenage boys growing up in a poor and run down area of Bradford, northern England. Arbor suffers from hyperactivity disorder, which often gets him into trouble even when it is not his intention. When the boys are suspended from school after a fight, they decide to earn money collecting and selling scrap metal. They quickly realize that stealing copper from telecom, railway, and power utilities can be lucrative.
They sell their scrap to a local scrap dealer, Kitten, who owns at least two horses and competes in amateur harness racing. Kitten allows Swifty to work with the horse, once he realizes Swifty's surprising affection for and natural talent with horses. Kitten also lets the boys borrow a horse and a cart to collect scrap metal.
Arbor is envious of Kitten's kindness toward Swifty. Arbor decides to steal pieces of scrap from Kitten and sell them, along with some other scrap, to a dealer in Huddersfield. The plan ends up backfiring; Arbor is refused entrance at the other dealer, and when he makes a deal with some men who offer to sell the scrap for him, they recognize it as stolen and keep the money. Kitten finds out and physically intimidates Arbor into stealing a specific piece of high voltage electric power transmission wire to make up for his loss. The boys are not fully aware of the dangers of high voltage wire. After Arbor cuts the wire, Swifty helps to lift it, but is electrocuted and killed.
Arbor is devastated and Kitten is arrested, telling the police he is responsible and allowing Arbor to escape blame. Arbor sits resolutely outside Swifty's mother's house until, after several rejections, his own mother finds him. In a final scene, Arbor takes care of the horse Swifty adored.<end_of_turn>
<start_of_turn>model
The film follows the lives of Arbor and Swifty, teenage boys growing up in a poor and run down area of Bradford, northern England. Arbor suffers from hyperactivity disorder, which often gets him into trouble even when it is not his intention. When the boys are suspended from school after a fight, they decide to earn money collecting and selling scrap metal. They sell their scrap to a local scrap dealer, Kitten, who owns at least two horses and competes in amateur harness racing.<end_of_turn>

label_ids:
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 818, 4103, 5238, 506, 6176, 529, 59400, 532, 4649, 59183, 236764, 41639, 12958, 6730, 872, 528, 496, 6934, 532, 1845, 1679, 2433, 529, 70802, 236764, 16962, 7591, 236761, 59400, 54992, 699, 233496, 18404, 236764, 837, 3187, 6757, 1515, 1131, 13007, 1581, 1056, 625, 563, 711, 914, 15925, 236761, 3026, 506, 12958, 659, 22235, 699, 2528, 1308, 496, 6093, 236764, 901, 10741, 531, 6637, 3273, 24595, 532, 11010, 28754, 6211, 236761, 2195, 6739, 910, 28754, 531, 496, 2263, 28754, 20220, 236764, 190923, 236764, 1015, 30047, 657, 3198, 1156, 17768, 532, 135766, 528, 49411, 36326, 18533, 236761, 106, 107]
labels:
The film follows the lives of Arbor and Swifty, teenage boys growing up in a poor and run down area of Bradford, northern England. Arbor suffers from hyperactivity disorder, which often gets him into trouble even when it is not his intention. When the boys are suspended from school after a fight, they decide to earn money collecting and selling scrap metal. They sell their scrap to a local scrap dealer, Kitten, who owns at least two horses and competes in amateur harness racing.<end_of_turn>

Running tokenizer on dataset (num_proc=16): 100%|█| 10000/10000 [00:28<00:00, 35
eval example:
input_ids:

# Inference

In [24]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from pprint import pprint

In [25]:
def generate_response(messages, max_new_tokens=1024):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

    generated_ids = model.generate(
        model_inputs.input_ids,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        top_k=None,
        temperature=None,
        top_p=None,
    )

    generated_ids = [
        output_ids[len(input_ids):]
        for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

    return response

In [37]:
base_model_id = "google/gemma-3-270m-it"
adapter_model_id = "/kaggle/working/finetuned_models/gemma3"

In [32]:
system = test_data.iloc[0]["system"]
input_text = test_data.iloc[0]["input"]
prompt = f'test_data.iloc[0]["instruction"] {input_text}'

In [35]:
test_data.iloc[0]["output"]

'When a flying saucer lands in Washington, D.C., the Army quickly surrounds it. A humanoid (Michael Rennie) emerges, announcing that he has come in peace. When he unexpectedly opens a small device, he is shot by a nervous soldier. A tall robot emerges from the saucer and quickly disintegrates the soldiers\' weapons. Klaatu escapes and lodges at a boarding house as "Mr. Carpenter"'

In [33]:
tokenizer = AutoTokenizer.from_pretrained(base_model_id)
model = AutoModelForCausalLM.from_pretrained(base_model_id,
                                             device_map="auto",
                                             torch_dtype=None)

## Base Model

In [34]:


messages = [
    {
        "role": "system",
        "content": system
    },
    {
        "role": "user",
        "content": prompt
    }
]
response = generate_response(messages)
print(response)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

Okay, I've analyzed the provided text. Here's a summary of the key events:

*   **Arrival and Initial Actions:** The Army surrounds the saucer, and a humanoid (Michael Rennie) emerges, announcing peace. He opens a small device, which is shot by a nervous soldier.
*   **The Alien's Arrival:** Klaatu, a tall, humanoid robot, emerges from the saucer and appears to be peaceful.
*   **The Alien's Motivation:** Klaatu's message is intended to be delivered to all world leaders simultaneously, which is impossible in the current political climate.
*   **The Alien's Actions:** Klaatu suggests that humans are irrational and have developed rockets and a rudimentary atomic power. He declares that if his message is ignored, Earth will be eliminated.
*   **Barnhardt's Arrival:** Barnhardt, a scientist, agrees to gather scientists from around the world.
*   **The Alien's Revelation:** Klaatu reveals his true identity as an interplanetary organization that created a police force of invincible robots, and he states that his message is a "peaceful demonstration."
*   **The Alien's Return:** Klaatu returns to his spaceship, unaware that Bobby has followed him.
*   **The Alien's Death:** Bobby sees Gort render two soldiers unconscious and Klaatu enter the saucer.
*   **The Alien's Actions:** Bobby tells Helen and Tom what he saw, but they do not believe him until Tom takes a diamond from Klaatu.
*   **The Alien's Identity:** Klaatu finds Helen at her workplace and they take an empty service elevator, which stops at noon. He has neutralized all electricity everywhere except for hospitals and aircraft.
*   **The Alien's True Identity:** Klaatu reveals his true identity to Helen, then asks for her help.
*   **The Alien's Reaction:** Helen breaks up with him. She and Klaatu go to Barnhardt's home.
*   **The Alien's Departure:** The alien, Klaatu, is shot dead. Helen quickly heads to the saucer. Gort kills two soldiers standing watch and advances on her.
*   **The Alien's Return:** Helen quickly heads to the saucer. Gort brings Klaatu back to life, but he explains to Helen that his revival is temporary.
*   **The Alien's Address:** Klaatu addresses Barnhardt's assembled scientists, informing them that he represents an interplanetary organization that created a police force of invincible robots.
*   **The Alien's Message:** Klaatu concludes, "Your choice is simple: join us and live in peace, or pursue your present course and face obliteration." Klaatu and Gort re-enter the spaceship and depart.

## Fine-tuned Model

In [38]:
model.load_adapter(adapter_model_id)

In [39]:

messages = [
    {
        "role": "system",
        "content": system
    },
    {
        "role": "user",
        "content": prompt
    }
]
response = generate_response(messages)
print(response)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.

A humanoid (Michael Rennie) emerges, announcing that he has come in peace. A tall robot emerges from the saucer and disintegrates the soldiers' weapons. The alien orders the robot to stop, and the alien orders the robot to stop. The alien, Klaatu, is taken to Walter Reed Hospital. Klaatu escapes and lodges at a boarding house as "Mr. Carpenter", the name on the dry cleaner's tag on a suit he took.